security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_db_provider:
            entity:
              class: App\Entity\User
              property: username

    encoders:
        App\Entity\User:
          algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: user_db_provider

            form_login:
                # The route name that the login form submits to
                check_path: login
                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                login_path: login
                # Secure the login form against CSRF
                # Reference: https://symfony.com/doc/current/security/csrf_in_login_form.html
                csrf_token_generator: security.csrf.token_manager
                # The page users are redirect to when there is no previous page stored in the
                # session (for example when the users access directly to the login page).
                default_target_path: post_list

            logout:
                # The route name the user can go to in order to logout
                path: logout
                # The name of the route to redirect to after logging out
                target: home

    access_control:
        - { path: ^/posts/new, roles: ROLE_ADMIN }
        - { path: ^/posts, roles: ROLE_ADMIN }
        - { path: ^/posts/\d+/delete, roles: ROLE_ADMIN }
        - { path: ^/posts/\d+/edit, roles: ROLE_ADMIN }

    access_decision_manager:
        strategy: affirmative
        allow_if_all_abstain: false